name: Trigger auto deployment for hackernews

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hackernews-AutoDeployTrigger-62b589ed-5414-4c65-ad9e-68ca6dddb637.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HACKERNEWS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HACKERNEWS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HACKERNEWS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: hackernews1si22is400.azurecr.io
          registryUsername: ${{ secrets.HACKERNEWS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HACKERNEWS_REGISTRY_PASSWORD }}
          containerAppName: hackernews
          resourceGroup: HackerNews
          imageToBuild: hackernews1si22is400.azurecr.io/hackernews:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


